# Generated by Django 3.1.4 on 2020-12-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board_state',
            field=models.CharField(default='', max_length=361),
        ),
    ]
