# Generated by Django 3.1.4 on 2021-01-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='playing_color',
            field=models.CharField(default='white', max_length=32),
        ),
        migrations.AddField(
            model_name='game',
            name='white_is_host',
            field=models.BooleanField(default=True),
        ),
    ]
