# Generated by Django 3.1.4 on 2020-12-30 11:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatline',
            name='chat_channel_code',
            field=models.CharField(default=api.models.generate_chat_channel_code, max_length=6),
        ),
    ]
