# Generated by Django 3.1.4 on 2021-01-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210101_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatline',
            name='sender',
            field=models.CharField(default='thanh', max_length=32),
        ),
    ]
