# Generated by Django 3.1.4 on 2020-12-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_playing', models.BooleanField(default=False)),
                ('is_spectating', models.BooleanField(default=False)),
                ('avatar_url', models.CharField(default='', max_length=255)),
                ('elo', models.IntegerField(default=1000)),
            ],
        ),
    ]
