# Generated by Django 3.1.4 on 2020-12-21 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(default='', max_length=255)),
                ('line', models.CharField(default='', max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.game')),
                ('sayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.player')),
            ],
        ),
    ]
