# Generated by Django 3.1.4 on 2020-12-21 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_chatline'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='chat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.chatline'),
        ),
        migrations.AddField(
            model_name='player',
            name='game_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.game'),
        ),
    ]
